aa/Models/Usuario.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace aa.Models
{
    public class Usuario
    {
        public enum Tipo
        {
            Funcionario,
            Lider
        }
        public int Id { get; set; }
        [Required]
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public int Idade { get; set; }
        [Required]
        public string CPF { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Senha { get; set; }
        [EmailAddress]
        [Required]
        public string Email { get; set; }
        public virtual ICollection<Tarefa> Tarefas { get; set; }
        [Required]
        public Tipo Cargo { get; set; }

        public virtual ICollection<Equipe> Equipes { get; set; }
        public virtual ICollection<Projeto> Projetos { get; set; }
        [DisplayName("Responsável")]
        public int ResponsavelId { get; set; }
    }
}

aa/Controllers/TarefaController.cs
using aa.BD;
using aa.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace aa.Controllers
{
    struct TarefaJson
    {
        public string Title;
        public string Desc;
        public string Start_Date;
        public string End_Date;

    }
    [RedirectingAction]
    public class TarefaController : Controller
    {
        private AppContext db = new AppContext();

        // GET: Tarefa
        public ActionResult Index()
        {
            return View(db.Tarefas.ToList());
        }

        // GET: Tarefa/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarefa tarefa = db.Tarefas.Find(id);
            if (tarefa == null)
            {
                return HttpNotFound();
            }
            return View(tarefa);
        }

        public void CriarSelectListResponsaveis()
        {
            var Usuarios = db.Usuarios.ToList();
            List<SelectListItem> lista = new List<SelectListItem>();
            foreach (var usu in Usuarios)
            {
                lista.Add(new SelectListItem { Value = usu.Id.ToString(), Text = usu.Nome });
            }
            ViewBag.Responsaveis = lista;
        }
        // GET: Tarefa/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tarefa/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Tarefa tarefa)
        {
            if (ModelState.IsValid)
            {
                tarefa.DataCriacao = DateTime.Now;
                tarefa.DataAlteracao = DateTime.Now;
                tarefa.Status = Status.NãoAtribuida;
                db.Tarefas.Add(tarefa);

                HistoricoTarefa historico = new HistoricoTarefa(db);
                historico.RegistrarAlteracao(TipoAlteracao.Inclusão, tarefa, ((Usuario)Session["Usuario"]).Id);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(tarefa);
        }

        // GET: Tarefa/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarefa tarefa = db.Tarefas.Find(id);
            if (tarefa == null)
            {
                return HttpNotFound();
            }

            CriarSelectListResponsaveis();
            return View(tarefa);
        }

        // POST: Tarefa/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Tarefa tarefa)
        {
            if (ModelState.IsValid)
            {
                tarefa.DataAlteracao = DateTime.Now;
                db.Entry(tarefa).State = EntityState.Modified;

                HistoricoTarefa historico = new HistoricoTarefa(db);
                historico.RegistrarAlteracao(TipoAlteracao.Edição, tarefa, ((Usuario)Session["Usuario"]).Id);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(tarefa);
        }

        // GET: Tarefa/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarefa tarefa = db.Tarefas.Find(id);
            if (tarefa == null)
            {
                return HttpNotFound();
            }
            return View(tarefa);
        }

        // POST: Tarefa/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult DeleteConfirmed(int id)
        {
            Tarefa tarefa = db.Tarefas.Find(id);
            if (tarefa == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            db.Tarefas.Remove(tarefa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpGet]
        public ActionResult Historico(int id)
        {
            List<HistoricoTarefa> listaHitorico = db.HistoricoTarefas.Where(x => x.TarefaId == id).ToList();
            HistoricoViewModel histView = new HistoricoViewModel(listaHitorico);
            return View(histView);
        }

       

        [HttpGet]
        public ActionResult ObterTarefasCalendario(string data = null)
        {
            JsonResult result = new JsonResult();
            List<Tarefa> tarefas = new List<Tarefa>();
            if (data == null)
            {
                tarefas = db.Tarefas.ToList();
            }
            else
            {
                var dataConvert = Convert.ToDateTime(data);
                tarefas = db.Tarefas.Where(x => x.DataEntrega.Month.Equals(dataConvert.Month)).ToList();
            }
            List<TarefaJson> tarefaJsons = new List<TarefaJson>();

            tarefas.ForEach(x =>
                tarefaJsons.Add(new TarefaJson
                {
                    Title = x.Titulo,
                    Desc = x.Descricao,
                    Start_Date = x.DataEntrega.ToString("yyyy-MM-dd"),
                    End_Date = x.DataEntrega.ToString("yyyy-MM-dd")
                })
            );

            result = Json(tarefaJsons, JsonRequestBehavior.AllowGet);
            return result;
        }


    }

}

aa/Controllers/UsuarioController.cs
using aa.BD;
using aa.Models;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace aa.Controllers
{
    [RedirectingAction]
    public class UsuarioController : Controller
    {
        private AppContext db = new AppContext();

        // GET: Usuario
        public ActionResult Index()
        {
            return View(db.Usuarios.ToList());
        }

        // GET: Usuario/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            if (usuario.ResponsavelId != 0)
            {
                ViewBag.Responsavel = db.Usuarios.Find(usuario.ResponsavelId).Nome;
            }

            return View(usuario);
        }

        // GET: Usuario/Create
        public ActionResult Create()
        {
            List<SelectListItem> lista = new List<SelectListItem>();
            List<Usuario> usu = db.Usuarios.ToList();
            usu.ForEach(x => lista.Add(new SelectListItem { Value = x.Id.ToString(), Text = x.Nome }));
            ViewBag.Responsaveis = lista;
            return View();
        }

        // POST: Usuario/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Usuario usuario)
        {

            if (ModelState.IsValid)
            {
                db.Usuarios.Add(usuario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(usuario);
        }

        // GET: Usuario/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }

            List<SelectListItem> lista = new List<SelectListItem>();
            List<Usuario> usu = db.Usuarios.ToList();
            foreach (var item in usu)
            {
                if (item.Id == usuario.ResponsavelId)
                {
                    lista.Add(new SelectListItem { Value = item.Id.ToString(), Text = item.Nome, Selected = true });
                }
                else
                {
                    lista.Add(new SelectListItem { Value = item.Id.ToString(), Text = item.Nome });
                }
            }
            lista.RemoveAt(lista.FindIndex(x => x.Value.Equals(id.ToString())));
            ViewBag.Responsaveis = lista;


            return View(usuario);
        }

        // POST: Usuario/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Usuario usuario)
        {
            if (usuario.ResponsavelId == usuario.Id)
            {
                ModelState.AddModelError("", "Não é possível vincular a si mesmo como responsável!!");
            }
            if (ModelState.IsValid)
            {
                db.Entry(usuario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(usuario);
        }

        // GET: Usuario/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // POST: Usuario/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult DeleteConfirmed(int id)
        {
            Usuario usuLogado = null;
            if (Session["Usuario"] != null)
            {
                usuLogado = (Usuario)Session["Usuario"];
            }
            if (usuLogado.Id == id)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            db.Usuarios.Remove(usuario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

aa/Views/Usuario/Create.cshtml
@model aa.Models.Usuario

@{
    ViewBag.Title = "Criar";

    List<SelectListItem> lista = new List<SelectListItem>();
    if (ViewBag.Responsaveis != null)
    {
        lista = (List<SelectListItem>)ViewBag.Responsaveis;
    }
}

<h2>Criar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Usuário</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sobrenome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Sobrenome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Sobrenome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Idade, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Idade, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Idade, "", new { @class = "text-danger" })
        </div>
    </div>

    @if (lista.Count > 0)
    {
        <div class="form-group">
            @Html.LabelFor(model => model.ResponsavelId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select id="ResponsavelId" class="form-control" name="ResponsavelId">
                    <option value="0">Selecione</option>
                    @foreach (var item in lista)
                    {
                        <option value="@item.Value">@item.Text</option>
                    }
                </select>
            </div>
        </div>

    }


    <div class="form-group">
        @Html.LabelFor(model => model.Cargo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(
    x => x.Cargo,
    "Selecione o cargo",
    new { @class = "form-control" })


            @Html.ValidationMessageFor(model => model.Cargo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvar usuário" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

aa/Views/Usuario/Delete.cshtml
@model aa.Models.Usuario

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

aa/Views/Usuario/Details.cshtml
@model aa.Models.Usuario

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes</h2>

<div>
    <h4>Usuário</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResponsavelId)
        </dt>

        <dd>
            @if (ViewBag.Responsavel != null)
            {
                @ViewBag.Responsavel
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tarefas)
        </dt>


        @foreach (var tar in Model.Tarefas)
        {
            <dd>
                @Html.ActionLink(tar.Titulo, "Details", "Tarefa", new { id = tar.Id }, null)
            </dd>
        }



    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Voltar a lista", "Index")
</p>

aa/Views/Usuario/Edit.cshtml
@model aa.Models.Usuario

@{
    ViewBag.Title = "Editar";

    List<SelectListItem> lista = new List<SelectListItem>();
    if (ViewBag.Responsaveis != null)
    {
        lista = (List<SelectListItem>)ViewBag.Responsaveis;
    }
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Usuário</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Email)


        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sobrenome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sobrenome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sobrenome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Idade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Idade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Idade, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (lista.Count > 0)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.ResponsavelId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <select id="ResponsavelId" class="form-control" name="ResponsavelId">
                        <option value="0">Selecione</option>
                        @foreach (var item in lista)
                        {
                            <option @(item.Selected ? "selected" : "") value="@item.Value">@item.Text</option>
                        }
                    </select>
                </div>
            </div>

        }

        <div class="form-group">
            @Html.LabelFor(model => model.Cargo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cargo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cargo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar a lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

aa/Views/Usuario/Index.cshtml
@model IEnumerable<aa.Models.Usuario>

@{
    ViewBag.Title = "Lista de Usuários";
    aa.Models.Usuario usuario = null;
    if (Session["Usuario"] != null)
    {
        usuario = (aa.Models.Usuario)Session["Usuario"];
    }
}




<h2>Lista de Usuários</h2>

@if (usuario != null && usuario.Cargo == aa.Models.Usuario.Tipo.Lider)
{
    <p>
        @Html.ActionLink("Criar Usuário", "Create", null, new { @class = "btn btn-primary" })
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sobrenome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cargo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr id="usuario_@item.Id">
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sobrenome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cargo)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Detalhes", "Details", new { id = item.Id })

                @if (usuario != null && usuario.Cargo == aa.Models.Usuario.Tipo.Lider)
                {

                    <span> |</span>
                    <a href="javascript:ExcluirUsuario(@item.Id)">Deletar</a>
                }

            </td>
        </tr>
    }

</table>

<script>
    function ExcluirUsuario(UsuarioId) {
        var r = confirm("Deseja realmente excluir esse usuário?");
        if (r == true) {
            $.ajax({
                url: "/Usuario/DeleteConfirmed/" + UsuarioId,
                method: "POST",
                success: function () {
                    $("#usuario_" + UsuarioId).remove();
                    toastr.success('Usuário excluido com sucesso!');
                    setTimeout(function () { $('#alertasucesso').hide(); }, 2500);
                },
                error: function () {
                    toastr.error('Erro ao excluir usuário!');
                    setTimeout(function () { $('#alertaerro').hide(); }, 2500);
                }
            });

        }
    }
</script>